---
title: 'Data File #1 Cleaning'
author: "Elle Holbrook"
date: "October 30, 2017"
output: html_document
---

```{r setup, include = FALSE, echo = FALSE}
library(tidyverse)
library(stringr)
library(readxl)
```

```{r loading the data}
xl <- read_excel("data/DRUG_CLASS_I_Mean_Cmax_Trough_Efficacy_R_DATA_ANALYSIS.xlsx")
lung_eff <- xl[2:12, ]
spleen_eff <- xl[17:26, ]
md1 <- xl[35:51, 1]
md2 <- c(xl[29, 3], xl[31, 3], xl[33, 3])
metadata <- full_join(md1, md2, by = NULL) ##how to combine cells from different columns into one?
```

```{r cleaning the data}
lung_eff %>% 
  rename(drug_name = MeanCmaxEfficacy,
         dose = X__1,
         PLA = X__2,
         ULU = X__3,
         RIM = X__4,
         OCS = X__5,
         ICS = X__6,
         SLU = X__7,
         SLE = X__8,
         ELU = X__9,
         ESP = X__10,
         cLogP = X__11,
         huPPB = X__12,
         muPPB = X__13,
         MIC_Erdman = X__14,
         MICserumErd = X__15,
         MIC_Rv = X__16,
         Caseum_binding = X__17,
         MacUptake = X__18) %>% 
  mutate(level = "Cmax",
         dosage = str_extract(dose, "[0-90-90-9]"),
         dose_int = str_extract(dose, "[A-ZA-ZA-Z]")) %>% 
  select(drug_name, dosage, dose_int, level, PLA:MacUptake)

spleen_eff <- spleen_eff %>% 
  rename(drug_name = MeanCmaxEfficacy,
         dose = X__1,
         PLA = X__2,
         ULU = X__3,
         RIM = X__4,
         OCS = X__5,
         ICS = X__6,
         SLU = X__7,
         SLE = X__8,
         ELU = X__9,
         ESP = X__10,
         cLogP = X__11,
         huPPB = X__12,
         muPPB = X__13,
         MIC_Erdman = X__14,
         MICserumErd = X__15,
         MIC_Rv = X__16,
         Caseum_binding = X__17,
         MacUptake = X__18) %>% 
  mutate(level = "Trough",
         dosage = ,
         dose_int = ) %>% 
  select(drug_name, dosage, dose_int, level, PLA:MacUptake)
```
