---
title: "Clean Data File 3"
author: "Brian Kim"
date: "November 1, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(stringr)
library(readxl)
library(ggplot2)
setwd("C:/Users/bkim7/R/input_output_shiny_group")
```

```{r load dataframe}
clean_3_cmax <- read_xlsx("DRUG_CLASS_I_Mean_Cmax_Trough_Efficacy_R_DATA_ANALYSIS.xlsx",
                  range = "PK!A3:J20") %>%
  mutate(dosage = str_extract(dose, "[0-9]+"),
          dose_interval = str_extract(dose, "[A-Z]+")) %>%
  select(-dose) %>%
  rename(mouse_number = `mouse number`)
  
clean_3_trough <- read_xlsx("DRUG_CLASS_I_Mean_Cmax_Trough_Efficacy_R_DATA_ANALYSIS.xlsx",
                  range = "PK!A24:J38") %>%
  rename(drug = X__1, dose = X__2, mouse_number = X__3) %>%
    mutate(dosage = str_extract(dose, "[0-9]+"),
          dose_interval = str_extract(dose, "[A-Z]+")) %>%
  select(-dose)
```

Now I am combining the two dataframes clean_3_cmax and clean_3_trough into a single dataframe
```{r combine trough and cmax}
clean_3 <- full_join(clean_3_cmax, clean_3_trough)
#write dataframe clean_3 to a csv file
write_csv(clean_3, path = paste0("C:/Users/bkim7/R/input_output_shiny_group/CSV_Files/clean_3.csv"))

```