---
title: "Katie_Efficacy"
author: "Katie Key"
date: "November 8, 2017"
output: html_document
---
## make it look like clean_2_combined.csv
mouse_id, compound, group, protocol_animal,
drug_dose, formulation, dose_frequency, days_treatment combined with treatment_interval


```{r, warning=FALSE,echo=FALSE,message=FALSE}

library(readxl)
library(readr)
library(tidyr)
library(dplyr)
library(utils)

```


```{r, warning=FALSE,echo=FALSE,message=FALSE}

efficacy <- read_excel("~/Documents/Colorado State/R_Programming_Directory/input_output_shiny_group/data/Gates_18 Efficacy R spreadsheet.xlsx")

efficacy_clean <- efficacy %>% 
  select(Protocol_Animal, Compound, Group, Drug_Dose, Days_Treatment,
         Treatment_Interval,Elung,Espleen) %>% 
  rename(lung_efficacy = Elung,
         spleen_efficacy = Espleen,
         dosage = Drug_Dose,
         days_treatment = Days_Treatment,
         dose_interval = Treatment_Interval,
         drug = Compound) %>%
  mutate(lung_efficacy = as.numeric(lung_efficacy)) %>% 
  mutate(spleen_efficacy = as.numeric(spleen_efficacy)) %>%
  mutate(dose_interval = as.factor(dose_interval)) %>%
  mutate(days_treatment = as.factor(days_treatment)) %>% 
  group_by(Protocol_Animal, drug, Group, dosage, days_treatment, dose_interval) %>% 
  summarize(lung_efficacy_log = log10(lung_efficacy),
            spleen_efficacy_log = log10(spleen_efficacy))

levels(efficacy_clean$dose_interval)[levels(efficacy_clean$dose_interval)=="Pre Rx 9 week"] <- "_Baseline"
levels(efficacy_clean$dose_interval)[levels(efficacy_clean$dose_interval)=="M-F"] <- "_QID"
levels(efficacy_clean$dose_interval)[levels(efficacy_clean$dose_interval)=="4 wk"] <- "20_Control"
levels(efficacy_clean$dose_interval)[levels(efficacy_clean$dose_interval)=="8 wk"] <- "40_Control"

efficacy_clean <- efficacy_clean %>% 
  unite(days_dose, days_treatment, dose_interval, sep = "") %>% 
  separate(days_dose, c("days", "dose"), sep = "_") %>% 
  rename("days_treatment" = days,
         "dose_interval" = dose) %>% 
  mutate(days_treatment = as.numeric(days_treatment))

head(efficacy_clean)

write_csv(efficacy_clean, path = paste0(getwd(), "/CSV_Files/clean_efficacy.csv")) 

```


```{r, warning=FALSE,echo=FALSE,message=FALSE}

# put this as a fileupload widget in the app ?


efficacy_data <- read_excel("~/Documents/Colorado State/R_Programming_Directory/input_output_shiny_group/data/Gates_18 Efficacy R spreadsheet.xlsx")

efficacy_function <- function(inputId){
  efficacy_clean <- efficacy %>% 
  select(Protocol_Animal, Compound, Group, Drug_Dose, Days_Treatment,
         Treatment_Interval,Elung,Espleen) %>% 
  rename(lung_efficacy = Elung,
         spleen_efficacy = Espleen,
         dosage = Drug_Dose,
         days_treatment = Days_Treatment,
         dose_interval = Treatment_Interval,
         drug = Compound) %>%
  mutate(lung_efficacy = as.numeric(lung_efficacy)) %>% 
  mutate(spleen_efficacy = as.numeric(spleen_efficacy)) %>%
  mutate(dose_interval = as.factor(dose_interval)) %>%
  mutate(days_treatment = as.factor(days_treatment)) %>% 
  group_by(Protocol_Animal, drug, Group, dosage, days_treatment, dose_interval) %>% 
  summarize(lung_efficacy_log = log10(lung_efficacy),
            spleen_efficacy_log = log10(spleen_efficacy))

levels(efficacy_clean$dose_interval)[levels(efficacy_clean$dose_interval)=="Pre Rx 9 week"] <- "_Baseline"
levels(efficacy_clean$dose_interval)[levels(efficacy_clean$dose_interval)=="M-F"] <- "_QID"
levels(efficacy_clean$dose_interval)[levels(efficacy_clean$dose_interval)=="4 wk"] <- "20_Control"
levels(efficacy_clean$dose_interval)[levels(efficacy_clean$dose_interval)=="8 wk"] <- "40_Control"

efficacy_clean <- efficacy_clean %>% 
  unite(days_dose, days_treatment, dose_interval, sep = "") %>% 
  separate(days_dose, c("days", "dose"), sep = "_") %>% 
  rename("days_treatment" = days,
         "dose_interval" = dose) %>% 
  mutate(days_treatment = as.numeric(days_treatment))
  DT::renderDataTable(efficacy_clean) 
  return(efficacy_clean)
}

efficacy_function()

```


