---
title: "Lizette_Laser_Capture"
author: "Lizette van Zyl"
date: "November 8, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(readxl)
read_csv("CSV_Files/clean_3.csv")

# setwd("~/Masters/R_Programming_Fall_2017/input_output_shiny_group")
```

```{r}
 # it is ok to add in the rows that are missing in order to map mice ids
 # assume that each grouping of 'outer, inner, rim, uninvolved' belongs to one mouse
 # by same looking at which mice had same compound, group, dosing, timepoint, and timepoint hours
   
las_file_to_clean <- "data/Gates_18_MALDI_Tissue Laser Capture R_liz_edit.xlsx"

clean_las_cap <- function(file_to_clean) {
  
     las_cap <- read_xlsx(file_to_clean) %>%
                rename(`Parent [ng/ml]` = Parent) %>%
                select(-StudyID, -Metabolite, - Units, - Collection, - `Sample ID`)

     n <- nrow(las_cap)
     mice_ids <- rep(c(1:(n/4)), each = 4)

     las_cap <- mutate(las_cap, MouseID = mice_ids) %>%
                spread(key = Compartment, value = `Parent [ng/ml]`) %>%
                rename(ULU = `uninvolved lung`, RIM = rim,
                       OCS = `outer caseum`, ICS = `inner caseum`) %>%
                mutate(ULU = as.numeric(ULU), RIM = as.numeric(RIM),
                       OCS = as.numeric(OCS), ICS = as.numeric(ICS))
     return(las_cap)
}

las_cap <- clean_las_cap(file_to_clean = las_file_to_clean)

write_csv(las_cap, path = paste0(getwd(), "/CSV_Files/clean_las_cap.csv"))
```

```{r}

```