---
title: "Plasma_Clean_Brian"
author: "Brian Kim"
date: "November 8, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(stringr)
```

Here I will read in the excel file
```{r read excel file}
plasma <- read_xlsx("data/Gates_18_MALDI_Plasma R.xlsx") 
```

Here I will seelct the variables I need and rename them
```{r clean the plasma file}
clean_plasma <- plasma %>%
  select(MouseID, 
         Compound, 
         Group, 
         Protocol_Animal, 
         Dosing, 
         Timepoint, 
         Plasma_Parent) %>%
  rename(drug = Compound, 
         mouse_number = MouseID, 
         plasma_concentration = Plasma_Parent) %>%
  mutate(Group = as.character(Group))
```

Here I write the data frame clean_plasma to a csv file
```{r clean_plasma to csv}
write_csv(clean_plasma, path = paste0("CSV_Files/clean_plasma.csv"))
```

Here I will write my cleaning code into a function called plasma_function
```{r plasma function}
plasma_function <- function(inputID){
  clean_plasma <- plasma %>%
  select(MouseID, 
         Compound, 
         Group, 
         Protocol_Animal, 
         Dosing, 
         Timepoint, 
         Plasma_Parent) %>%
  rename(drug = Compound, 
         mouse_number = MouseID, 
         plasma_concentration = Plasma_Parent)
}
```