---
title: "Input/Output/Shiny Group"
author: "Elle Holbrook, Katie Key, Brian Kim, Lizette Van Zyl"
output: ioslides_presentation
runtime: shiny
---
########################################
ui, what server code looks like, what actual output looks like

####################

##Outline for Presentation:

1. Group Goals
2. Idea development
3. Datasets
4. Tidying process
5. Shiny app development
6. Challenges
7. What we would do differently
8. Interesting observations
9. Possible errors
10. Conclusions

########################

## Group Goals

- Load original Excel files from the research group into R
- Clean the data into "tidy" (or useable) formats
- Develop an R Shiny App that displays summaries of the clean data and
  displays interactive graphs created by the other groups

########################

## Idea Development

- Originally planned to combine all data into one large dataset
- Learned that individual Excel files could not be combined because they used
  different mice: switched to cleaning all datasets individually
- Worked backwards from summary templates to clean original files
- Shiny app layout developed as files were cleaned and Independent/Dependent
  groups shared visuals they wanted included

########################

## Datasets

Each group member cleaned one orginal data file to match the summarized version
provided at the beginning of the project.

- Efficacy (Katie)
- Plasma (Brian)
- Tissue Laser (Lizette)
- Tissue Standard PK (Elle)

########################

## Tidying Process

- fix original files that had missing rows
- input dummy ids for columns that had no information (mice ids)
- `select` down to only relevant columns
- `gather` or `spread` data to make control easier for visuals groups

########################

##Shiny app development

- 

```{r, echo=FALSE, warning=FALSE,message=FALSE, fig.height=4, fig.width=8}


```

########################

## Challenges

- differences between spreadsheets  
- what information research group wanted  
- Shiny app  

########################

## What we would do differently

- communicate with research group earlier on  
- communicate with other groups for efficiency  
- create "test" version of app that doesn't have to load files every time while
  developing the app

########################

## Interesting observations

- one mouse can only be used for so many measurements  



########################

## Possible errors

- Too few/missing columns in input dataframe
- Wrong column names
- Inputting data in format other than Excel
- Different data class in columns
- Missing rows in orginal files instead of using NAs
- Inputting values in differing units throughout file
  (won't break code but will mess up analysis)

########################
## Conclusions

- how real world data is not always tidy  
- reward to create the Shiny app  

########################

